name: TNTRun
main: tntrun.TNTRun
softdepend: [WorldEdit, Vault]
version: 1.0
author: [_Shevchik_]
commands:
  tntrunsetup:
    description: TNTRun arena setup commands
    aliases: trsetup
  tntrun:
    description: TNTRun game commands
    aliases: tr
  tntrunconsole:
    description: TNTRun console commands
    aliases: trconsole